import Head from 'next/head'

interface Iprops {
  statusCode: number
}
function Error({ statusCode }: Iprops) {
  return (
    <div>
      <Head>
        <title>demo image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Erorororro: {statusCode}</main>
    </div>
  )
}
Error.getInitialProps = ({ res, err }: { res: any; err: any }) => {
  console.log(res)
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return { statusCode }
}

export default Error
