import { Box } from '@mui/material'
import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import TestImage from '~/public/images/test.jpeg'
const demoimage: NextPage = () => {
  // load by size
  const renderImage = () => {
    return <Image src={TestImage} objectFit="cover" alt="1231" layout="fill" />
  }
  //lazy load image
  // const renderImage = () => {
  //   return [1, 2, 3, 4, 5].map((item) => {
  //     return (
  //       <Box key={item}>
  //         <Image src={TestImage} width={500} height={300} objectFit="cover" layout="fill"  />
  //       </Box>
  //     );
  //   });
  // };
  return (
    <div>
      <Head>
        <title>demo image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <p>heheh</p>
        {renderImage()}
      </Box>
    </div>
  )
}

export default demoimage
